#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKI.TOOL.IR.CHECK.data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Wrapper")]
	public partial class DbWrapperDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DbWrapperDataContext() : 
				base(global::OKI.TOOL.IR.CHECK.Properties.Settings.Default.WrapperConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DbWrapperDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbWrapperDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbWrapperDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbWrapperDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<t_IR_Search_result> t_IR_Search_results
		{
			get
			{
				return this.GetTable<t_IR_Search_result>();
			}
		}
		
		public System.Data.Linq.Table<t_IR_result> t_IR_results
		{
			get
			{
				return this.GetTable<t_IR_result>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_IR_Search_result")]
	public partial class t_IR_Search_result
	{
		
		private int _no;
		
		private System.Nullable<int> _job_no;
		
		private string _kotei_filename;
		
		private string _unit_no;
		
		private string _st_no;
		
		private System.Nullable<System.DateTime> _start_time;
		
		private System.Nullable<System.DateTime> _finish_time;
		
		private string _remarks;
		
		private System.Nullable<System.DateTime> _time_access;
		
		private string _pcline;
		
		public t_IR_Search_result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int no
		{
			get
			{
				return this._no;
			}
			set
			{
				if ((this._no != value))
				{
					this._no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_no", DbType="Int")]
		public System.Nullable<int> job_no
		{
			get
			{
				return this._job_no;
			}
			set
			{
				if ((this._job_no != value))
				{
					this._job_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kotei_filename", DbType="VarChar(255)")]
		public string kotei_filename
		{
			get
			{
				return this._kotei_filename;
			}
			set
			{
				if ((this._kotei_filename != value))
				{
					this._kotei_filename = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unit_no", DbType="VarChar(50)")]
		public string unit_no
		{
			get
			{
				return this._unit_no;
			}
			set
			{
				if ((this._unit_no != value))
				{
					this._unit_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_no", DbType="VarChar(100)")]
		public string st_no
		{
			get
			{
				return this._st_no;
			}
			set
			{
				if ((this._st_no != value))
				{
					this._st_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> start_time
		{
			get
			{
				return this._start_time;
			}
			set
			{
				if ((this._start_time != value))
				{
					this._start_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_finish_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> finish_time
		{
			get
			{
				return this._finish_time;
			}
			set
			{
				if ((this._finish_time != value))
				{
					this._finish_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remarks", DbType="VarChar(MAX)")]
		public string remarks
		{
			get
			{
				return this._remarks;
			}
			set
			{
				if ((this._remarks != value))
				{
					this._remarks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time_access", DbType="DateTime")]
		public System.Nullable<System.DateTime> time_access
		{
			get
			{
				return this._time_access;
			}
			set
			{
				if ((this._time_access != value))
				{
					this._time_access = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pcline", DbType="VarChar(100)")]
		public string pcline
		{
			get
			{
				return this._pcline;
			}
			set
			{
				if ((this._pcline != value))
				{
					this._pcline = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_IR_result")]
	public partial class t_IR_result
	{
		
		private int _job_no;
		
		private string _worker;
		
		private string _kotei_filename;
		
		private System.Nullable<int> _kotei_no;
		
		private string _unit_no;
		
		private System.Nullable<int> _result;
		
		private System.Nullable<System.DateTime> _start_time;
		
		private System.Nullable<System.DateTime> _finish_time;
		
		private string _st_no;
		
		private string _errorcode;
		
		private string _errorname;
		
		private string _remarks;
		
		private string _batname;
		
		private string _tplog;
		
		public t_IR_result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_no", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int job_no
		{
			get
			{
				return this._job_no;
			}
			set
			{
				if ((this._job_no != value))
				{
					this._job_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_worker", DbType="NVarChar(100)")]
		public string worker
		{
			get
			{
				return this._worker;
			}
			set
			{
				if ((this._worker != value))
				{
					this._worker = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kotei_filename", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string kotei_filename
		{
			get
			{
				return this._kotei_filename;
			}
			set
			{
				if ((this._kotei_filename != value))
				{
					this._kotei_filename = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kotei_no", DbType="Int")]
		public System.Nullable<int> kotei_no
		{
			get
			{
				return this._kotei_no;
			}
			set
			{
				if ((this._kotei_no != value))
				{
					this._kotei_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unit_no", DbType="VarChar(50)")]
		public string unit_no
		{
			get
			{
				return this._unit_no;
			}
			set
			{
				if ((this._unit_no != value))
				{
					this._unit_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_result", DbType="Int")]
		public System.Nullable<int> result
		{
			get
			{
				return this._result;
			}
			set
			{
				if ((this._result != value))
				{
					this._result = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> start_time
		{
			get
			{
				return this._start_time;
			}
			set
			{
				if ((this._start_time != value))
				{
					this._start_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_finish_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> finish_time
		{
			get
			{
				return this._finish_time;
			}
			set
			{
				if ((this._finish_time != value))
				{
					this._finish_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_no", DbType="NVarChar(100)")]
		public string st_no
		{
			get
			{
				return this._st_no;
			}
			set
			{
				if ((this._st_no != value))
				{
					this._st_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_errorcode", DbType="NVarChar(100)")]
		public string errorcode
		{
			get
			{
				return this._errorcode;
			}
			set
			{
				if ((this._errorcode != value))
				{
					this._errorcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_errorname", DbType="NVarChar(100)")]
		public string errorname
		{
			get
			{
				return this._errorname;
			}
			set
			{
				if ((this._errorname != value))
				{
					this._errorname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remarks", DbType="NVarChar(MAX)")]
		public string remarks
		{
			get
			{
				return this._remarks;
			}
			set
			{
				if ((this._remarks != value))
				{
					this._remarks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_batname", DbType="NVarChar(300)")]
		public string batname
		{
			get
			{
				return this._batname;
			}
			set
			{
				if ((this._batname != value))
				{
					this._batname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tplog", DbType="NVarChar(MAX)")]
		public string tplog
		{
			get
			{
				return this._tplog;
			}
			set
			{
				if ((this._tplog != value))
				{
					this._tplog = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
